import express from "express";
import path from "node:path";
import {fileURLToPath} from "node:url";
const app=express(), __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use(express.json({limit:"10mb"}));
app.use(express.static(path.join(__dirname,"public")));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"DIMRI Model & Fan Studio",version:"0.1.1"}));
app.post("/api/generate",(req,res)=>{const {mode="free",modelId=null,prompt="",settings={}}=req.body||{};if(!prompt.trim())return res.status(400).json({ok:false,error:"Prompt is required"});res.json({ok:true,status:"provider_pending",message:"Generation request accepted. Connect a real image/video provider API to render final media.",job:{id:"job_"+Date.now(),mode,modelId,prompt,settings}})});
app.use((req,res,next)=>{if(req.method!=="GET")return next();res.sendFile(path.join(__dirname,"public","index.html"))});
app.listen(process.env.PORT||10000,()=>console.log("DIMRI Model & Fan Studio online"));